### ISSUE TITLE
-m32 doesn't work

### ISSUE THREAD

**Issue by ysangkok** [docker-library/gcc#11]
I'm trying to compile busybox for 32-bit platforms:

```
In file included from /usr/include/limits.h:27:0,
                 from /usr/local/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/include-fixed/limits.h:168,
                 from /usr/local/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/include-fixed/syslimits.h:7,
                 from /usr/local/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/include-fixed/limits.h:34,
                 from include/platform.h:141,
                 from include/libbb.h:13,
                 from include/busybox.h:8,
                 from applets/applets.c:9:
/usr/include/features.h:323:26: fatal error: bits/predefs.h: No such file or directory
 #include <bits/predefs.h>
                          ^
compilation terminated.
make[1]: *** [applets/applets.o] Error 1
make: *** [applets_dir] Error 2
INFO[0044] The command [/bin/sh -c python -c "import urllib; urllib.urlretrieve('http://www.busybox.net/downloads/busybox-1.23.1.tar.bz2','/dev/stdout')" | tar jx && (cd busybox-1.23.1 && export TGTARCH=i486 && make defconfig && LDFLAGS="--static" make EXTRA_CFLAGS=-m32 EXTRA_LDFLAGS=-m32 && ln busybox ../initramfs/busybox-i486) && rm -rf busybox-1.23.1] returned a non-zero code: 2
```

Thanks in advance.

**Comment by yosifkit** [comment]
I don't think we specifically include any of the 32-bit libraries that would be required for this type of cross-compilation.

Also, why the python `urllib.urlretrieve` when both `wget` and `curl` are available in the image?

**Comment by ysangkok** [comment]
Are we talking about the same image? I'm referring to gcc:4.9.2. I just checked, I find the curl library and headers there, but no binary.

**Comment by yosifkit** [comment]
Sorry,  I thought we fixed that it erroneously installs and [removes](https://github.com/docker-library/gcc/blob/master/4.9/Dockerfile#L37) wget and curl, even though it is in the base `buildpack-deps`.

**Comment by tianon** [comment]
Is this still an issue?  If it is, would [using the `i386/gcc` image](https://hub.docker.com/r/i386/gcc/) instead be an acceptable workaround?

**Comment by larsbrinkhoff** [comment]
I just ran into this.  Test case:

    $ docker run -it gcc /bin/bash
    root@eeb0489e4ac1:/# cat > tmp.c
    int main (void) { return 0; }
    root@eeb0489e4ac1:/# gcc -m32 tmp.c
    /usr/bin/ld: cannot find crt1.o: No such file or directory
    /usr/bin/ld: cannot find crti.o: No such file or directory
    /usr/bin/ld: skipping incompatible /usr/local/lib/gcc/x86_64-pc-linux-gnu/6.2.0/libgcc.a when searching for -lgcc
    /usr/bin/ld: cannot find -lgcc
    /usr/bin/ld: cannot find -lgcc_s
    /usr/bin/ld: cannot find -lc
    /usr/bin/ld: skipping incompatible /usr/local/lib/gcc/x86_64-pc-linux-gnu/6.2.0/libgcc.a when searching for -lgcc
    /usr/bin/ld: cannot find -lgcc
    /usr/bin/ld: cannot find -lgcc_s
    /usr/bin/ld: cannot find crtn.o: No such file or directory
    collect2: error: ld returned 1 exit status

**Comment by larsbrinkhoff** [comment]
I use both `gcc -m32` and `gcc -m64` in my builds, so `i386/gcc` would not be a complete solution.

**Comment by liudonghua123** [comment]
I have the same problem.

**Comment by GottZ** [comment]
literally ran into this problem by trying to compile a valve source engine plugin with gcc / g++ 7

why is there just no tagging for this stuff..
i'd love to see something like gcc:7-multilib on docker hub instead of building my own gcc image.. (wich i did.. but i doubt everyone knows how to do that)

also weird that gcc and g++ are not present in /usr/bin but /usr/local/bin or something like that.

**Comment by tianon** [comment]
At this point, I think it's safe to say we don't really have any good ideas for how to fix this, nor do we have any plans to work on it very hard. :innocent:

I'm going to close this now -- what I would suggest for folks who need this is probably something like one of the following (in order of how much I'd personally choose them if I were solving this problem for myself):

- use `FROM i386/debian:bullseye-slim` and install just the necessary packages (including `gcc`)
- use `FROM debian:bullseye-slim` and add `i386` as a foreign architecture (to then install what's necessary)
- use `FROM i386/buildpack-deps:bullseye` (which already includes `gcc` and the same set of libraries/development packages as this image does)
