### ISSUE TITLE
GCC docker gcc:latest does not have binutils version2.41 required for AMX-COMPLEX support

### ISSUE THREAD

**Issue by VictorRodriguez** [docker-library/gcc#110]
According to the binutils support:
https://sourceware.org/git/?p=binutils-gdb.git;a=commitdiff;h=d100d8c1f316acbef7dfd75d09b44b5e23b0bb8a
https://www.phoronix.com/news/GNU-Binutils-2.41-Branched

The GCC requires at least BINUTILS 2.41 version to build the AMX-COMPLEX instructions, currently the latest image has: 

```
docker run -it gcc:latest bash
root@d95e1906ab70:/# ld --version
GNU ld (GNU Binutils for Debian) 2.40
Copyright (C) 2023 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
```

Which breaks the build as: 

```
0.675 gcc  -O2 -mamx-complex -mavx512fp16 amxcomplex-cmmimfp16ps-2.c -o amxcomplex-cmmimfp16ps-2
1.093 amxcomplex-cmmimfp16ps-2.c: Assembler messages:
1.093 amxcomplex-cmmimfp16ps-2.c:48: Error: no such instruction: `tcmmimfp16ps %tmm3,%tmm2,%tmm1'
```

tested with own build of binutils 2.41 works ok 

Would be nice to have an update on the docker hub image for this release of binutils to have a proper gcc docker image that help us to build AMX-COMPLEX ISA

**Comment by yosifkit** [comment]
Unfortunately, `2.40` is all that is available in Debian Bookworm (https://packages.debian.org/bookworm/binutils). Unless there is a backport of `2.41` or `2.42`, we'll likely have to wait for the next Debian release to get the newer `binutils` package.
