### ISSUE TITLE
There's no 'make' command in the gcc image

### ISSUE THREAD

**Issue by antonyh** [docker-library/gcc#12]
There doesn't appear to be a make command in the image. ```find / -name 'make'``` returns nothing, as does ```which make``` and ```whereis make```. 
```
docker run --rm -it gcc:4.9.2 make     
exec: "make": executable file not found in $PATH2015/04/01 22:52:42 Error response from daemon: Cannot start container 31845b91f2b2654817d2350812b5522e2629b51e6a032380e6533e142dc35be8: exec: "make": executable file not found in $PATH
```
and also:
```
docker run --rm -it gcc:4.9.2 /bin/bash
root@02e5ffc9ba1a:/# make
bash: make: command not found
root@02e5ffc9ba1a:/# 
```

**Comment by antonyh** [comment]
This also appears to be true for 4.8

**Comment by yosifkit** [comment]
Oops, this was fixed with #10.  I am working right now to merge the changes to docker-library/official-images so that the changes will get pushed up.

**Comment by yosifkit** [comment]
Thanks for the reminder.

**Comment by yosifkit** [comment]
https://github.com/docker-library/official-images/pull/632 for status on when it will be available.

**Comment by antonyh** [comment]
Thank you for the speedy response.

**Comment by tianon** [comment]
:+1:
