### ISSUE TITLE
Wrong libstdc++.so.6 found

### ISSUE THREAD

**Issue by thewtex** [docker-library/gcc#18]
When compiling my library, I get:

  /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found

when running executables.

Adding LD_LIBRARY_PATH=/usr/local/lib64 fixes the issue.

Should this variable be added to the image or the path added to /etc/ld.so.conf.d/ ?

**Comment by tianon** [comment]
Oh, I wonder if we need to invoke `ldconfig` after we finish building.  Does invoking `ldconfig` before you build your library work too (without setting `LD_LIBRARY_PATH`)?

**Comment by thewtex** [comment]
Nope, ldconfig before building yields the same result.
