### ISSUE TITLE
compiling C program failed. library missing

### ISSUE THREAD

**Issue by learningtjrs** [docker-library/gcc#35]
Gentlemen, 
i was trying to compile a "C" program inside the "gcc" container, but it is giving me an error:
"fatal error: conio.h: No such file or directory
 #include <conio.h>
                   ^
compilation terminated."
why there is no "conio.h" library inside the container, and if possible how we can add it?

thank you

**Comment by Moghedrin** [comment]
`conio.h` is a Windows library, so it's definitely not going to in the `gcc` image by default, since the container is a Linux environment. You're probably trying to compile a Windows specific program, if it includes that particular library.

**Comment by learningtjrs** [comment]
so, you are saying that i cannot run and compile "C" programs on docker, because there is something related to windows.

**Comment by tianon** [comment]
C is tricky in that getting your dependencies and headers is a _very_ manual process.  In this case, you can get `conio.h` installed in a container (see https://packages.debian.org/file:conio.h for hints), but `conio.h` is a Windows-specific header (as can be seen by the names of the packages there -- those are Wine and/or MinGW packages).

If your goal is to compile Windows C programs into `.exe` files for running on a Windows system, you're going to need a compiler built for that -- the compiler included in this image is stock `gcc`, and is compiled on Linux (for amd64 specifically) to create binaries for that same target system.

I would recommend looking into MinGW for the application you're trying to compile (which is `gcc` modified and recompiled to build `.exe` files specifically for Windows).

**Comment by learningtjrs** [comment]
i understand, that you very much @tianon  for your kind explanation
