### ISSUE TITLE
Push 6.4 to dockerhub

### ISSUE THREAD

**Issue by bijancn** [docker-library/gcc#39]
Have you maybe forgotten to push to docker hub or is there a fixed schedule? The docker file has been updated 6 days ago https://github.com/docker-library/gcc/commit/c1fe37de30fbe69e83f042b4a9426b11cb624bca.

**Comment by yosifkit** [comment]
It was added to the official images in https://github.com/docker-library/official-images/pull/3147.  Our build server got bogged down and it must've been missed in the builds after maintenance.  I have restarted the build, so it should be up shortly.

**Comment by bijancn** [comment]
Thanks a lot!
