### ISSUE TITLE
Latest GCC 8 images using Debian:Jessie?

### ISSUE THREAD

**Issue by sadatnfs** [docker-library/gcc#46]
Not sure if this was intentional but when I pulled the newest GCC 8 images, all of them were pointing to using Debian:Jessie as opposed to Stretch when I last pulled a month ago, and the Dockerfile also seems to build from Stretch. Any idea why this could be happening?

Here's my log from when I `cat` the `os-release` in `/etc`

```
root@XXXXXXXXXXX:/# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"```

**Comment by tianon** [comment]
Whoops, looks like this was another instance of https://github.com/docker-library/ruby/issues/216 -- I've kicked off a build now (https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/gcc/68/console). :+1:

**Comment by sadatnfs** [comment]
Looks good now on the latest pull! Thanks!
