### ISSUE TITLE
libxml2-dev

### ISSUE THREAD

**Issue by stenzing** [docker-library/gcc#47]
I was trying to use the system to compile a program which uses libxml dependencies, so I created the dockerfile to install libxml2-dev before compiling. The apt reported that libxml2-dev is already installed, but the compiler cannot find any headers from the lib, and also I checked the directories with ls, to check and there were also no libxml dev files.
 The dockerfile is the following:

`FROM gcc
COPY . /root
WORKDIR /root
RUN apt-get install -y libxml++*
RUN gcc -o decrypt decrypt.c
`

**Comment by wglambert** [comment]
The image GCC is built from is `buildpack-deps:stretch` which includes `apt get install libxml2-dev`

The files are located in `/usr/include/libxml2`
```console
root@4e0a1ae904bc:/# pkg-config --cflags libxml-2.0
-I/usr/include/libxml2
```

So you could update your Dockerfile to do `gcc $(pkg-config --cflags libxml-2.0) ...`

If you're still having issues you could create a simple C file to reproduce

**Comment by stenzing** [comment]
Hi!

Thanks I got on the same result afterwards :) It was years ago I last did C devel in bash, and missed the fact, that I have to add the linked files to the parameter list.

Thanks.
