### ISSUE TITLE
/usr/src/gcc increasing image size

### ISSUE THREAD

**Issue by KevinWMatthews** [docker-library/gcc#51]
Is there a reason that `/usr/src/gcc/` isn't deleted after the build is finished? In gcc:8.2.0 that particular directory is 774M, if I'm using `du` properly.

It seems like the source code shouldn't be required for the gcc executable to run. Are there other reasons that container users might need access to the source? If not, we could reduce the image size significantly.

**Comment by yosifkit** [comment]
Neat, this has been in the images since their creation in 2014 (by me :cry:), but I would consider it a bug and not a feature.

Opened a PR: #53
