### ISSUE TITLE
Multi-stage build?

### ISSUE THREAD

**Issue by KevinWMatthews** [docker-library/gcc#52]
Food for thought: have you considering using a [multi-stage build](https://docs.docker.com/develop/develop-images/multistage-build/)?

If done well, it could be used to run clone, configure, compile, and/or install steps separately. Given the length of your compile step, this could be handy for you as the image developers. It's also useful for avoiding issues like that in #51 .

I realize that you can't necessarily make a sweeping change to your Dockerfile templates - this is a shipping version of gcc, after all. And perhaps you need to support Docker versions older than 17.05? But if it's just because no one has taken the time to put in the work, I can make PR as a starting point for discussion.

**Comment by wglambert** [comment]
We can't use multi-stage builds at this time: docker-library/official-images#3383.
