### ISSUE TITLE
Wrong logo on Docker Hub

### ISSUE THREAD

**Issue by bit2shift** [docker-library/gcc#54]
The logo used on the Docker Hub page should be changed to the official one.
[![GCC logo](https://gcc.gnu.org/img/gccegg-65.png)](https://gcc.gnu.org/img/gccegg-65.png)

**Comment by yosifkit** [comment]
It is on the Hub description; we don't have control over the one at the top or in search results. I'll hit up Docker folks to see if they can update it.

https://hub.docker.com/_/gcc/
