### ISSUE TITLE
fails to rebuild image with docker 18.09.6 on Debian/buster

### ISSUE THREAD

**Issue by Trophime** [docker-library/gcc#58]
Trying to rebuild gcc:9.1.0 image from scratch
I run into this error:
```
+ gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys B215C1633BCA0477615F1B35A5B3A004745C015A
gpg: directory '/root/.gnupg' created
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: keyserver receive failed: Cannot assign requested address
The command '/bin/sh -c set -ex; 	for key in $GPG_KEYS; do 		gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; 	done' returned a non-zero code: 2
```

**Comment by wglambert** [comment]
https://github.com/docker-library/official-images/issues/4252#issuecomment-381783035
>TLDR; GPG servers are extremely flaky . . .

This is what we do for GPG issues https://github.com/docker-library/official-images/issues/4252#issuecomment-405749749

If you try a few more times it should go through
