### ISSUE TITLE
Alpine/musl-libc variant

### ISSUE THREAD

**Issue by J0WI** [docker-library/gcc#59]
Debian provides `musl-gcc` in the `musl-tools` package and it's the standard C library in Alpine Linux.

**Comment by tianon** [comment]
Given how heavy building "gcc" from source is (and how readily
available precompiled "gcc" packages are in Alpine and Debian), I'm
personally -1 on this.

We've honestly considered more than once deprecating this image
entirely with a similar justification.

**Comment by yosifkit** [comment]
Finally coming back to this. :bowing_man:

This is not something we have room to add (maintenance and build time). We recommend using distribution-provided packages.
