### ISSUE TITLE
Hello, I am a newbie, may I ask this to run Objective-C?

### ISSUE THREAD

**Issue by RanX12** [docker-library/gcc#63]
Hello, I am a newbie, may I ask this to run
Objective-C?
Thanks

**Comment by wglambert** [comment]
Yeah GCC will compile Objective-C 

https://www.maheshsubramaniya.com/article/hello-world-in-objective-c-and-compiling-with-gcc.html
https://gcc.gnu.org/onlinedocs/gcc/Objective-C-and-Objective-C_002b_002b-Dialect-Options.html

**Comment by tianon** [comment]
That being said, this image probably will not because we don't enable Objective-C when we build `gcc`:

https://github.com/docker-library/gcc/blob/aab71caeb1be048b44fd140a102cb7f17f995276/9/Dockerfile#L122
