### ISSUE TITLE
broken link https://git.savannah.gnu.org/cgit/config.git/plain/$f?id=7d3d27baf8107b630586c962c057e22149653deb

### ISSUE THREAD

**Issue by blackerking** [docker-library/gcc#69]
Like in the titel said:
https://git.savannah.gnu.org/cgit/config.git/plain/$f?id=7d3d27baf8107b630586c962c057e22149653deb

This link is broken.

**Comment by tianon** [comment]
If you look at the context where that appears in the `Dockerfile`, the `$f` bit is a variable that gets replaced with `config.guess` and `config.sub`:

https://github.com/docker-library/gcc/blob/7f1fc5e8be598446b2546b808572db546e959643/Dockerfile.template#L82-L87

So the real links would be:

- https://git.savannah.gnu.org/cgit/config.git/plain/config.guess?id=7d3d27baf8107b630586c962c057e22149653deb

- https://git.savannah.gnu.org/cgit/config.git/plain/config.sub?id=7d3d27baf8107b630586c962c057e22149653deb

(Which as you can see, do work properly.)
