### ISSUE TITLE
Add Ada support and GNAT compiler

### ISSUE THREAD

**Issue by btmalone** [docker-library/gcc#70]
I am not sure the state of this project based on this [comment](https://github.com/docker-library/gcc/issues/59#issuecomment-511064381), but would it be possible to include gnat as one of the compilers build from gcc? I figure since gfortran is supported I do not think is a huge stretch to include gnat as well.

I made a fork of this repo and made the changes to support everything needed for Ada and it can be found [here](https://github.com/btmalone/gcc-1). If this is something that would be feasible then I will make a pull request.

**Comment by tianon** [comment]
I'd be really curious why you're interested in having a (quite large) compiled-from-source `gcc` Docker image instead of something simpler (and smaller) like `FROM debian:buster-slim` and installing https://packages.debian.org/buster/gnat?  What's the benefit that this image provides over that?

**Comment by btmalone** [comment]
Tbh I do not really know what that use case of this image is. As you said this is a rather bloated image with everything installed. Since this image is well over a 1GB I don't see it as a practical image to use for most things. (I do have a smaller gnat image using apt-get that I use as a more suitable runtime) Personally I see this image as more pedagogical in that it shows how to download and compile GCC from source.

Maybe one use case would be that it lets you build gcc binaries from source in a known environment. So I could make a gcc binary from source and then using docker cp get the binary out of the image and than that could be the official binary version? But I am not sure if that is even a feasible or even a good idea.

**Comment by tianon** [comment]
Sorry for the delay -- I'm going to close this as we have no plans to add support for Ada or GNAT at this time. :sweat_smile:
