### ISSUE TITLE
Slim image

### ISSUE THREAD

**Issue by jheaff1** [docker-library/gcc#73]
Hi,

Currently the gcc docker images are roughly 400MB in size. Would it be possible for there to be a slim variant that contains minimal packages, e.g. bash and gcc only?

**Comment by tianon** [comment]
This is very closely related to https://github.com/docker-library/gcc/issues/59 -- I'd suggest that if you aren't picky about the precise version of `gcc` you get, you're probably better off with something like this:

```dockerfile
FROM debian:buster-slim
RUN apt-get update && apt-get install -y gcc
```

(Which will net you a ~200MB image.)

**Comment by jheaff1** [comment]
Ideally I would like a slim docker image with glibc (rather than musl) a precise version of gcc. 

I would then use this Docker image along with Bazel to build all of my dependencies from source - even tools like GNU Make

**Comment by tianon** [comment]
I guess the easy way to get what you're looking for is something like this:

```dockerfile
FROM debian:buster-slim
COPY --from=gcc:10.3 /usr/local/ /usr/local/
```

This will be pretty close to what we would build if we did end up building a "slim" variant (and it comes in at around 450MB, compared to the 1.19GB of `gcc:10.3`).

If you want to get that size down, I'd suggest doing a multi-stage build and deleting things you don't need (like possibly all the Go-related files) in the first stage.

**Comment by jheaff1** [comment]
That’s a great idea, I’ll give that a go. Thanks!

**Comment by superlbr** [comment]
@tianon well, `COPY --from=gcc:10.3` run with error
1. `ld: no such file or directory`, then install `binutils`
2. `ld: cannot find -lm: no such file or directory`
    `ld: cannot find -lpthread: no such file or directory`
    ...many errors
3. use `gcc:bookworm` just work
