### ISSUE TITLE
/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found

### ISSUE THREAD

**Issue by dismine** [docker-library/gcc#78]
Hi.

I use this image to test my code with GCC 11. It builds code successfully, but fail to run a program with following error ``/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found``. It seems something missing.

**Comment by tianon** [comment]
Gonna need a bit more detail to reproduce your issue -- maybe you have a minimal example `.c` file and `Dockerfile` we can use to replicate?

**Comment by tianon** [comment]
(FWIW, Debian Experimental now has GCC 11 as well.)

**Comment by dismine** [comment]
Cannot reproduce on small example. I switched to another image.
