### ISSUE TITLE
cc: command not found

### ISSUE THREAD

**Issue by suchja** [docker-library/gcc#9]
Hi,
I'm using the gcc:4.9 image to try to build a software. I created a Dockerfile using gcc:4.9, adding the required packages via apt-get and finally cloned the source code from github. When I now start the required make && make install, one of the first error messages says

/bin/sh: 1: cc: not found

Probably this isn't an issue with the image, but how do you suggest to properly debug to find the root cause? Are there any other logs? Can I somehow trace what exactly is going wrong within the container?

Thanks and regards
Jan

**Comment by suchja** [comment]
While investigating on this I found that there is usually a link from cc -> gcc in /usr/bin/. This does not exist in my container. Is that by default?

**Comment by suchja** [comment]
Okay, got my software compiled. Problem was the following statement in Makefile `CC ?= gcc`. I guess this checks whether gcc is available. Maybe somehow it got the impression that it wasn't. I changed the above line to `CC = gcc` and everything is fine.
So it looks to me that this might be some sort of problem with the gcc container.

**Comment by yosifkit** [comment]
it seems most distributions make a symlink to `cc` for backwards compatibility for old projects (http://www.computerhope.com/unix/ucc.htm, https://forums.gentoo.org/viewtopic-t-947474-start-0.html).

Should we add the symlink to this image?

**Comment by mpapierski** [comment]
I think its safe to assume `gcc` image should contain `cc`, `c89` and `c99` symlinks.

SUS[1] defines `cc` as "an interface to an unspecified C-language compilation system. The system conceptually consists of a preprocessor, compiler, optimiser, assembler and link editor.". It also defines `c89` in similiar way.

There is also "c99"[2] utility which is successor of "c89" as defined in POSIX. Interesting thing is that newest POSIX does not specify cc. Only c99[3].

[1]: http://pubs.opengroup.org/onlinepubs/007908799/xcu/cc.html
[2]: http://pubs.opengroup.org/onlinepubs/009695399/utilities/c99.html
[3]: http://pubs.opengroup.org/onlinepubs/9699919799/

**Comment by yosifkit** [comment]
Sounds reasonable to me to add all 3 symlinks.

**Comment by suchja** [comment]
Yes, sounds good. 
Actually I would like to do it myself, if that is possible. Unfortunately I haven't done a contribution myself at all. So I guess I only need to fix it and send you a pull request right? Or is there anything else to do? Is it properly tested when it builds on my machine or are there any additional tests?

**Comment by yosifkit** [comment]
Yep, fork it, fix it, and make a PR.  We don't have any tests for gcc yet, so build and run is fine.  I look forward to your contribution, thanks :smile:.  If you need any help or have any other questions, we are here.

**Comment by suchja** [comment]
After looking a little deeper into this I don't think the simple symlinks are well suited. For `cc`this should be fine. However, `c89`and `c99` are actually small shell wrapper scripts calling gcc with specific options (e.g. `gcc -std=c89`). Those scripts seem to be distribution specific. 
They are available in the container already until the initially installed gcc gets removed by `apt-get purge -y --auto-remove curl gcc g++ wget`. Why is gcc removed anyway? From my tests it seems that the image, which is already pretty large, doesn't get any smaller by removing gcc and the other programs.

So I would suggest we leave the initially installed `gcc` and `g++` (which is version 4.7), simply add 4.9 and use `update-alternatives` to set 4.9 as the default version to be used. So we keep the default gcc environment from debian. Thus it seems to me that we have a more consistent gcc environment.

**Comment by tianon** [comment]
We purge the existing `gcc` simply to ensure that users of the image don't accidently get the "wrong" GCC (because you're correct that purging it can't affect the size due to the way Docker image layers work).

**Comment by suchja** [comment]
Implemented in #10.
